/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package me.tankery.app.helloswig.jni;

public class hello {
  public static String get_hello() {
    return helloJNI.get_hello();
  }

}
