/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package me.tankery.app.helloswig.jni;

public class LengthGetter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LengthGetter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LengthGetter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        music_wrapJNI.delete_LengthGetter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    music_wrapJNI.LengthGetter_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    music_wrapJNI.LengthGetter_change_ownership(this, swigCPtr, true);
  }

  public int get() {
    return music_wrapJNI.LengthGetter_get(swigCPtr, this);
  }

  public LengthGetter() {
    this(music_wrapJNI.new_LengthGetter(), true);
    music_wrapJNI.LengthGetter_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
