/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package me.tankery.app.helloswig.jni;

public class music_wrapJNI {
  public final static native void delete_LengthGetter(long jarg1);
  public final static native int LengthGetter_get(long jarg1, LengthGetter jarg1_);
  public final static native long new_LengthGetter();
  public final static native void LengthGetter_director_connect(LengthGetter obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void LengthGetter_change_ownership(LengthGetter obj, long cptr, boolean take_or_release);
  public final static native void delete_Music(long jarg1);
  public final static native float Music_getTime(long jarg1, Music jarg1_, long jarg2, LengthGetter jarg2_);
  public final static native void Music_fileCount_set(int jarg1);
  public final static native int Music_fileCount_get();
  public final static native long new_Mp3Music();
  public final static native void delete_Mp3Music(long jarg1);
  public final static native float WavMusic_getTime(long jarg1, WavMusic jarg1_, long jarg2, LengthGetter jarg2_);
  public final static native long new_WavMusic();
  public final static native void delete_WavMusic(long jarg1);
  public final static native long Mp3Music_SWIGUpcast(long jarg1);
  public final static native long WavMusic_SWIGUpcast(long jarg1);

  public static int SwigDirector_LengthGetter_get(LengthGetter jself) {
    return jself.get();
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
