/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package me.tankery.app.helloswig.jni;

public class Music {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Music(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Music obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        music_wrapJNI.delete_Music(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public float getTime(LengthGetter arg0) {
    return music_wrapJNI.Music_getTime(swigCPtr, this, LengthGetter.getCPtr(arg0), arg0);
  }

  public static void setFileCount(int value) {
    music_wrapJNI.Music_fileCount_set(value);
  }

  public static int getFileCount() {
    return music_wrapJNI.Music_fileCount_get();
  }

}
