/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package me.tankery.app.helloswig.jni;

public class WavMusic extends Music {
  private long swigCPtr;

  protected WavMusic(long cPtr, boolean cMemoryOwn) {
    super(music_wrapJNI.WavMusic_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WavMusic obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        music_wrapJNI.delete_WavMusic(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public float getTime(LengthGetter arg0) {
    return music_wrapJNI.WavMusic_getTime(swigCPtr, this, LengthGetter.getCPtr(arg0), arg0);
  }

  public WavMusic() {
    this(music_wrapJNI.new_WavMusic(), true);
  }

}
